from pathlib import Path
import json,collections,gzip,csv
out=Path(__file__).resolve().parent
sheets=[]
def col(name,typ,desc,unit,constraint,editable=True):return {'column':name,'type':typ,'description_zh':desc,'unit':unit,'constraint':constraint,'editable':editable}
def sheet(name,pk,columns,target,note):sheets.append({'sheet':name,'entity_id':name,'primary_key':pk,'columns':columns,'json_targets':target,'note':note})
order=col('order','int','固定输出/随机选择顺序；物理行排序不改变它','0起序号','按作用域唯一且连续；与冻结基线同ID同序号；锁定；导出必须按它排序',False)
def ident(name,description):return col(name,'string',description,'稳定ID','仅已有实现/已验ID；不自动新增功能；非空；主键作用域唯一',False)
def foreign(name,description,owner,editable=True):return col(name,'string',description,'已有ID引用',f'必须存在于{owner}；保持当前引用，变更需跨表校验',editable)
key=ident('key','现有或本次明确规划的配置键')
dtype=col('data_type','enum','本键固定数据类型，不随单元格显示格式改变','类型标签','int/float/bool/string/null；必须符合键契约；锁定',False)
value=col('value','typed_literal','按本键固定类型读入的单一字面值','见unit列','拒绝公式；不得把数字放进文本；null键用空值且类型为null；有限值；每键专属范围见KEY_CONTRACT',True)
unit=col('unit','string','值的中文单位与比例口径','说明','必填；只作说明，不改变数值计算',False)
desc=col('description','string','中文用途/联动说明','说明','必填；不参与JSON业务值',False)
constraint=col('constraint','string','固定范围/外键/不可编辑理由','说明','必填；以代码契约执行，不能编辑此文案绕过校验',False)
editable=col('editable','bool','该键是否真实允许调整；不是功能开关','权限标签','锁定并匹配契约；false拒绝改离基线',False)
sheet('标量配置',['key'],[key,dtype,value,unit,desc,constraint,editable],['hyperspace_config.json root scalars'], '不包含版本号；仓储/保护键移到相应页；新增现代化基础系数1与自动20/100；已有放大起点4接线；所有默认数值不变。')
sheet('仓储保留',['key'],[key,dtype,value,unit,desc,constraint,editable],['hyperspace_config.json warehouse_capacity/overflow_capacity/reforge_capacity_gain/initial_retention_capacity/retention_capacity_gain/maximum_equipped/maximum_legendary/maximum_ultimate'], 'overflow容量10及已有硬上限约束锁定；封存领取的星球门槛引用原planet/unlock表，不复制。')
sheet('保护与策略',['key'],[col('key','string','保护参数或已存在policies子键','稳定键','允许清单，路径映射由契约指定',False),dtype,value,unit,desc,constraint,editable],['hyperspace_config.json completion/filter/forecast limits and policies'], '过滤器用户条件/mode/action/预设是玩家保存状态，不放进Excel；未消费策略仅说明并锁定；版本、触发深度、保护引用、审核状态保持代码不变量。')
sheet('路线',['route_id'],[order,ident('route_id','现有alpha/beta/gamma/delta路线'),foreign('weapon','路线武器结构绑定；四个既有ID唯一覆盖','现有装备/敌武器注册表',False),ident('material','现有专属材料结构ID；与改造成本及存档一致')],['hyperspace_config.json /routes'], '四路线、四武器对应关系完整且唯一；顺序保留。')
sheet('品质',['quality'],[order,ident('quality','现有white/blue/gold/legendary来源品质'),col('affix_limit','int','可生成/改造的词缀槽位上限','槽','非负；不超过既有0/2/3/3硬上限'),col('hanging_limit','int','可生成挂设槽位上限','槽','非负；不超过既有4/2/1/0硬上限'),col('weapon_level_bonus','int','来源品质武器有效等级增量；非究极时蓝来源优先，蓝转传说仍用蓝加成','武器有效等级增量','非负；蓝来源继承规则不改'),col('dismantle_amount','int','拆解专属材料数与随机挂设副本数','份/次','正整数；现行为同一个数，不拆成两个可独立调参来源；奖励校验上界联动')],['hyperspace_config.json /quality_limits,/weapon_level_bonuses,/dismantle_amounts'], '究极有效等级奖励仍是标量ultimate_weapon_bonus；不伪装为第五种origin_quality。')
sheet('奖励权重',['outcome'],[order,ident('outcome','white/blue/gold/legendary/ultimate_core抽签结果'),col('weight','float','结果相对抽签权重；单独调大更易抽中该结果，调小更少；实际概率=本权重/总权重，不要求总和1','相对权重','非负；合计>0；默认合计1.09，不能当互斥绝对概率')],['hyperspace_config.json /quality_weights'], '按order构建有序Dictionary；核心固定一次一个及独占/额外政策由既有支持规则控制，不添加送机/赠核心。')
sheet('舰型槽位',['hull_id'],[order,foreign('hull_id','现有舰型ID','ship.xlsx',False),col('capacity','int','该舰型无人机装备容量；调大可同时生效更多机，调小更少；仍受全局上限约束','架','1..5，且满足全局maximum_equipped')],['hyperspace_config.json /hull_capacities'], '只引用舰型ID，不复制舰体数值/普通武器槽。')
sheet('阶级权重',['tier'],[order,col('tier','int','现有词缀阶级，1为最高','阶','1..5完整唯一',False),col('draw_weight','float','新生成阶及升阶判定的相对权重；调大本阶更易抽中，强于当前阶才成功且只升1阶','相对权重','>0；保留默认1/5/15/45/135及order'),col('modernization_weight','float','无人机每个词缀按其阶加入此费用系数；调大该阶现代化更贵，调小更便宜，另加基础系数','无量纲','非负；保留默认10/5/3/1/0.5；与draw_weight是不同用途，不混为一项')],['hyperspace_config.json /tier_weights,/modernization_tier_weights'], '两列分别导出两个有序字典，阶键序1→5保持。')
sheet('词缀定义',['affix_id'],[order,ident('affix_id','已实现聚合器支持的词缀ID'),col('weapon','string','适用武器；空字符串代表全局','武器ID/空字符串','已支持武器或空；空保持为""而非null；结构绑定必须基线等值',False),col('amplified','bool','固定：是否按等级放大已有词缀值','bool','必须基线等值；不改变词缀行为',False)],['hyperspace_config.json /affixes/*/weapon,/amplified'], '抽词缀候选池按order排列。')
sheet('词缀区间',['affix_id','tier'],[foreign('affix_id','词缀定义外键','词缀定义',False),col('tier','int','该词缀有定义的阶级','阶','1..5；仅导出存在的阶，不凭空补缺',False),col('minimum','float','未放大的原值区间下端','原始加成；1=100%或数量','有限；≤maximum；value_precision网格至少有一个可取值'),col('maximum','float','未放大的原值区间上端','同minimum','有限；≥minimum；数量词缀现有量化及最终int投影保持')],['hyperspace_config.json /affixes/*/ranges'], '范围输出[minimum,maximum]；tier字典按固定1..5顺序输出，不能随物理行变化。')
sheet('改造费用',['operation','resource'],[col('operation_order','int','已有改造操作输出顺序','0起序号','固定操作顺序，锁定',False),ident('operation','已有Forge操作ID'),foreign('resource','现有材料或ultimate_cores','路线材料与核心账本'),col('amount','int','该改造操作基础资源消耗；调大更贵，调小更便宜；结算及UI共用，部分操作另乘锁定/保底系数','份/次','非负整数；同(operation,resource)唯一；真实preview/commit共用此来源')],['hyperspace_config.json /forge_costs'], '允许同操作多资源行但仅已实现资源；没有现代化空cost行：现代化实际价格来自公式，不能增加第二份报价权威。')
sheet('挂设',['module_id'],[order,ident('module_id','既有五种挂设ID'),col('base_exp','float','首份只解锁不给经验；重复模块输入经验及各级阈值共用base_exp','经验/重复模块','>0且有限'),col('exp_growth','float','升级所需经验按base_exp×(1+此值)^当前等级；调大后续升级更慢，调小更快','比例；1=100%','≥0且有限，经验需求不得非有限'),col('effect_growth','float','每架加成=(1+此值)^全局模块等级−1；调大高等级收益更强，调小更弱；等级0为0，同类多架相加','比例；1=100%','≥0且有限，实际公式pow(1+g,L)-1保持'),col('unlock_stage','int','挂设生效所需最高已到达关；调大更晚生效，调小更早，不是模块经验等级','关','非负整数'),col('effects_note','string','当前effects数组的说明，仅标签非路由','只读说明','从基线说明映射；不编辑扩玩法；原JSON effects数组由锁定契约保留',False)],['hyperspace_config.json /hanging_modules'], '拆解随机挂设选择按order；实际module→消费者映射留在代码，旧effects不当可调开关。')
sheet('传说定义',['effect_id'],[order,ident('effect_id','既有十二种传说效果ID'),col('weapon','string','固定结构绑定；空字符串表示全武器通用','武器ID/空字符串','仅已有武器或空字符串；结构绑定必须基线等值',False),col('score_parameter_note','string','当前强弱比较读取第一个parameter键','只读参数名','保持当前首参数或空；只是说明，不新增可调primary策略',False)],['hyperspace_config.json /legendary_effects/*/weapon'], '随机效果候选池按order；不增加效果ID/行为。')
sheet('传说区间',['effect_id','parameter'],[foreign('effect_id','传说定义外键','传说定义',False),order,ident('parameter','该效果已实现参数名'),col('minimum','float','新生成/重洗范围下端','依参数；倍率/比例','≤maximum、有限、量化网格非空；比例类满足既有语义范围'),col('maximum','float','新生成/重洗范围上端','同minimum','≥minimum；不得混入旧存值许可范围'),col('stored_minimum','float_or_blank','仅已有stored_parameter_ranges下端','旧存值许可','仅现有兼容项填；否则空并不输出该键；锁定；不做旧档迁移',False),col('stored_maximum','float_or_blank','仅已有stored_parameter_ranges上端','同stored_minimum','成对出现，当前既有0.8..0.9保留；锁定',False)],['hyperspace_config.json /legendary_effects/*/parameters,/stored_parameter_ranges'], 'order按每effect作用域唯一连续；生成parameters字典必须按order；第一个参数用于现有强弱比较。')
sheet('传说常量',['effect_id','constant_path'],[foreign('effect_id','传说定义外键','传说定义',False),col('constant_path','string','效果内固定常量路径，如quality_ratios/white','相对字段路径','仅当前支持的已知路径，不接受脚本/任意表达式',False),dtype,value,unit,desc,constraint,editable],['hyperspace_config.json /legendary_effects/*/constants'], '数值常量有精确键约束；counting_policy和maximum_towers未消费，锁定；源码固定行为不因表格化扩展。')
sheet('异空间敌人',['enemy_id'],[order,col('enemy_id','int','现有独立异空间敌人ID','ID','正整数，当前223个既有ID；不得与主线ID冲突',False),col('description','string','已有敌人描述','文本','必须基线等值；不创造美术/新指南',False),col('size','int','既有舰体尺寸档','尺寸档','正整数且现有模型/几何支持'),col('health','number','独立异空间敌人基础生命；调大更耐打、推进更慢，调小反之；战斗再乘所选主线lifeRatio','生命','>0且有限'),col('armour_type','int','装甲抗性类别','枚举码','0/1/2'),col('shield','number','敌人基础护盾；调大更耐打，调小更少；随所选主线lifeRatio缩放，0为无护盾','护盾','≥0且有限'),col('shield_type','int','护盾抗性类别','枚举码','0/1/2'),col('shield_recovery','number','每秒按最大护盾恢复的比例；调大护盾恢复更快，调小更慢；需超过命中后延迟','比例/游戏秒','≥0且有限'),col('shield_delay','number','实际命中后等待多久才恢复护盾；调大更晚恢复、易持续压制，调小更早；每次实际命中刷新','游戏秒','≥0且有限'),col('damage_multiplier','number','异空间敌武器基础伤害倍率；调大敌人更危险，调小更弱；再继承所选主线atkRatio，不改变资源收入倍率','无量纲','≥0且有限')],['space_enemy_candidates.json /enemies'], 'equipment另表；drops/rewardDrops/jewelDropRolls/res由奖励投影重建或保持冻结非编辑基线，不提供第二份预算。')
sheet('敌人武器',['enemy_id','order'],[col('enemy_id','int','异空间敌人外键','ID','必须存在于异空间敌人',False),order,foreign('weapon_id','现有敌武器安装键','enemy_weapon_base.xlsx/现有ShipDatabase.enemy_weapon')],['space_enemy_candidates.json /enemies/*/equipment'], '每行一项安装，重复武器按不同order保留；不复制装备伤害/CD等正式表参数。')
sheet('异空间编队',['group_id'],[order,col('group_id','int','现有四十组独立编队ID','ID','正整数，当前7001..7040既有集合，不与主线冲突',False),col('description','string','已有编队名称/描述','文本','必须基线等值；不创造新描述',False),col('tier','enum','普通/精英/Boss/地区Boss档位','档位','normal/elite/boss/ultimate；总计16/16/4/4，当前不扩组'),foreign('reward_reference_id','奖励预算设计参考键','奖励参考')],['space_enemy_candidates.json /groups'], '固定15槽的null结构由编码器模板重建；审核版本/status/acceptance元数据不作为可编辑值。')
sheet('编队槽位',['group_id','slot_index'],[col('group_id','int','编队外键','ID','必须存在于异空间编队',False),col('slot_index','int','源15槽的实际索引','0起索引','0..14，group内唯一，不能自动密排'),col('enemy_id','int','该非空槽异空间敌人','ID','必须存在于异空间敌人'),col('x','number','显式阵型横坐标','逻辑战场单位','有限且54..518；实际几何合法'),col('y','number','显式阵型纵坐标','逻辑战场单位','有限且80..350；大型舰前后顺序/中心扇区合法')],['space_enemy_candidates.json /groups/*/slots,/formation_positions'], '仅写非空槽；未列槽保留null，不能变成0；占用槽必须有x/y。既有显式阵型验证负责几何约束。')
sheet('路线编队',['route_id','tier','order'],[foreign('route_id','异空间路线外键','路线',False),col('tier','enum','战斗档位','档位','normal/elite/boss/ultimate固定顺序',False),order,col('group_id','int','该档位有序编队ID','ID','存在于异空间编队且档位一致；每路线4/4/1/1，无跨路线重复')],['space_enemy_routes.json /routes'], 'JSON以路线表weapon键投影；按route.order、固定tier次序、组order输出；倍率继承策略仍是固定规则，不另设倍率表。')
sheet('奖励参考',['reference_id'],[ident('reference_id','现有奖励参考设计键'),col('source_design_group_id','int','现有正式主线原设计组引用','ID','存在于正式monGroup；仅引用，不复制预算'),col('late_reference_level_id','int','现有晚段回退引用关卡','关卡ID','存在于正式level且对应group确属该关卡'),col('late_reference_group_id','int','现有晚段回退引用组','group ID','存在于正式monGroup；真实blocks从mon的drops读取'),col('boundary_note','string','既有早1..5、晚≥6规则与不可重建项','只读说明','锁定；不把catalog未消费分界字段当参数',False)],['space_enemy_candidates.json /groups/*/rewardBinding/rewardReferenceDesignId','space_enemy_reward_catalog.json references association only'], 'reference_member_count从正式source_design组非空槽派生（当前40/40相等）；晚段budget不在表里重复。早段fallback及sources原设计来源仍用冻结派生JSON基线，本轮无伪造重生成。')
sheet('奖励成员分配',['group_id','slot_index','reference_member_ordinal'],[col('group_id','int','异空间奖励组外键','ID','存在于异空间编队',False),col('slot_index','int','实际收取该预算块的异空间非空槽','0起索引','必须为该组非空槽'),col('reference_member_ordinal','int','被分配的原参考成员序号','0起索引','覆盖0..reference_count-1且无重复；每个非空槽有成员记录，允许零预算')],['space_enemy_reward_recipes.json /groups'], '一行一个分配，不复制奖励金额；enemy_id从group.slot派生，jewelDropRolls=该槽ordinal数。导出成员按slot_index，ordinal按当前顺序；若当前非升序须加局部order列，不能私自排序。')
# Every proposed column has a complete human contract; physical sheet count remains author choice.
for s in sheets:
 for c in s['columns']:assert all(c[k] for k in ['column','type','description_zh','unit','constraint'])
contract={'status':'authoring draft, no workbook/code changes','source_commit':'f9d31b92d2b80af1c4b663173f12e4f6a23b8841','workbook_filename_recommendation':'retain hyperspace_config.xlsx identity; upgrade importer for entity sheets','physical_partition':'Logical sheet defaults below are concrete; parent may combine views/files through explicit manifest mapping. Count is not an approval requirement.','layout':{'row1':'exact English column names','row2':'Chinese description + unit + constraint (can wrap line breaks)','row3':'fixed declared column type','row4_plus':'literal typed data; no formulas','notes':'Parent spreadsheet tool authors workbook. No openpyxl writing/export_config regeneration here.'},'ordering':{'order_zero_based':True,'order_protected':True,'physical_row_sort_ignored':True,'scope':'See each entity primary key; effect parameter order scoped to effect; route groups scoped to route+tier; mounts to enemy; dictionaries must match CURRENT_DICTIONARY_ORDER.json','new_ids_or_orders':'Rejected outside separately authorized schema changes'},'rules_outside_editable_cells':['config/save/filter/RNG schema versions','single-depth triggers/protected references/refund/idempotency','fixed40 encounter acceptance metadata and15slot template','fixed automatic full-cap dispatch and actual completed mainline ratio inheritance','fixed core reward1/preset count3/unimplemented prism maximum_towers/counting_policy','1960 primary-derived wave mappings and historical provenance'],'sheets':sheets}
(out/'SHEET_COLUMN_CONTRACT.json').write_text(json.dumps(contract,ensure_ascii=False,indent=2)+'\n')
with (out/'SHEET_COLUMN_CONTRACT.tsv').open('w',encoding='utf-8',newline='') as f:
 w=csv.DictWriter(f,fieldnames=['sheet','primary_key','column','type','description_zh','unit','constraint','editable'],delimiter='\t');w.writeheader()
 for s in sheets:
  for c in s['columns']:w.writerow({'sheet':s['sheet'],'primary_key':'+'.join(s['primary_key']),**c})
(out/'ORDER_CONTRACT.txt').write_text('所有order列0起，在其作用域内唯一、连续、按冻结ID固定并锁定；工作表行随意排序不得改变order。输出Dictionary须按order插入，Array按原索引或显式order。基线CURRENT_DICTIONARY_ORDER.json完整覆盖当前对象序列。品质奖励顺序white,blue,gold,legendary,ultimate_core；tier1..5；路线alpha,beta,gamma,delta；词缀/挂设/传说效果池按基线order；传说参数首键决定既有强弱比较，不能按字母重排。编队slots空位仍null，slot_index不得密排。奖励ordinal数组若含非升序，须增加order保留原序，不按数值猜重排。\n')
print('Concrete logical sheets',len(sheets),'fully described columns',sum(len(s['columns']) for s in sheets))
