extends "test_missile_retarget.gd"
func released(g):
 commit(g,0,g.enemies[0]);step(g,0)
 return g.projectiles[0]
func run()->void:
 var g=fixture(1);g.speed=10
 var shot=released(g);var origin=Vector2(shot.x,shot.y)
 step(g,1./60.)
 check(absf(shot.motion_age-1./60.)<1e-9 and Vector2(shot.x,shot.y)==origin,"merged movement does not defer logical age")
 var frozen=g.projectiles.duplicate(true);var clock=g.motion_clock;var rng=g.rng.state
 g.paused=true;g.tick(.5)
 check(g.projectiles==frozen and g.motion_clock==clock and g.rng.state==rng,"pause freezes pending movement, age, queue and RNG")
 g.paused=false;g.speed=1;step(g,1./60.)
 var reference=fixture(1);var expected=released(reference)
 step(reference,1./60.);step(reference,1./60.)
 check(not shot.has("fast_motion_elapsed") and Vector2(shot.x,shot.y)==Vector2(expected.x,expected.y) and shot.motion_age==expected.motion_age,"X10 to X1 flushes credited interval without double aging")
 for i in 30:step(g,1./60.);step(reference,1./60.)
 check(g.projectiles==reference.projectiles and g.rng.state==reference.rng.state,"continued X1 path remains exact")
 g=fixture(1);g.speed=10;shot=released(g);step(g,1./60.)
 var heading=shot.direction;g.enemies[0].hp=0;step(g,.001)
 check(shot.target.is_empty() and shot.direction==heading,"death loses lock immediately even between merged movement updates")
 advance(g,10)
 check(g.projectiles.is_empty() and g.hit_records.is_empty() and g.orphan_expirations==0,"orphan coasts offscreen without damage or short expiry")
 g=fixture(1);g.speed=10;shot=released(g);shot.motion_age=4.49;step(g,.02)
 check(shot.dead and g.lifetime_expirations==1 and not shot.has("fast_motion_elapsed"),"guided lifetime is checked on exact clock before movement threshold")
 g=fixture(1);g.speed=10;shot=released(g);step(g,1./60.);g.spawn_group();step(g,.001)
 check(shot.target.is_empty() and not shot.dead,"ordinary wave preserves released orphan")
 g=fixture(1);g.speed=10;shot=released(g);step(g,1./60.)
 g.group_index=g.db.levels[g.stage-1].groups.size();g.hit_enemy(g.enemies[0],1e100,1,[],false);g.tick(1./60.)
 check(g.projectiles.is_empty() and g.missile_queue.is_empty(),"terminal group clears merged projectiles and ejections")
 g=fixture(1);g.speed=10;shot=released(g);step(g,1./60.)
 g.player.armour=0.;g.begin_retreat();g.tick(.1)
 check(g.missile_queue.is_empty() and g.hit_records.is_empty() and (shot.dead or shot.target.is_empty()),"death cancels ejections and invalidates targets without ghost hits")
 g.tick(2.0)
 check(shot.dead and not g.projectiles.has(shot),"death keeps ordinary coasting until offscreen cleanup, without detached interval")
 g=fixture(1);g.speed=10;shot=released(g);step(g,1./60.);var count=g.launch_records.size()
 g.leave(BattleGame.State.MAIN_MENU);g.tick(.5)
 check(g.projectiles.is_empty() and g.launch_records.size()==count,"leaving battle never advances detached movement")
 g.start(1,false)
 check(g.projectiles.is_empty() and g.missile_queue.is_empty(),"restart clears all old flight/ejection ownership")
 print("FAST MISSILE LIFECYCLE: ",checks," checks, ",failures," failures")
 quit(1 if failures else 0)
